-- Alters the npc_text column names to usefull ones
-- How to apply these updates see Evildead666_Big_Backport.sql


ALTER TABLE npc_text CHANGE COLUMN em0_0 em0_0_delay SMALLINT(5);
ALTER TABLE npc_text CHANGE COLUMN em0_1 em0_0 SMALLINT(5);
ALTER TABLE npc_text CHANGE COLUMN em0_2 em0_1_delay SMALLINT(5);
ALTER TABLE npc_text CHANGE COLUMN em0_3 em0_1 SMALLINT(5);
ALTER TABLE npc_text CHANGE COLUMN em0_4 em0_2_delay SMALLINT(5);
ALTER TABLE npc_text CHANGE COLUMN em0_5 em0_2 SMALLINT(5);

ALTER TABLE npc_text CHANGE COLUMN em1_0 em1_0_delay SMALLINT(5);
ALTER TABLE npc_text CHANGE COLUMN em1_1 em1_0 SMALLINT(5);
ALTER TABLE npc_text CHANGE COLUMN em1_2 em1_1_delay SMALLINT(5);
ALTER TABLE npc_text CHANGE COLUMN em1_3 em1_1 SMALLINT(5);
ALTER TABLE npc_text CHANGE COLUMN em1_4 em1_2_delay SMALLINT(5);
ALTER TABLE npc_text CHANGE COLUMN em1_5 em1_2 SMALLINT(5);

ALTER TABLE npc_text CHANGE COLUMN em2_0 em2_0_delay SMALLINT(5);
ALTER TABLE npc_text CHANGE COLUMN em2_1 em2_0 SMALLINT(5);
ALTER TABLE npc_text CHANGE COLUMN em2_2 em2_1_delay SMALLINT(5);
ALTER TABLE npc_text CHANGE COLUMN em2_3 em2_1 SMALLINT(5);
ALTER TABLE npc_text CHANGE COLUMN em2_4 em2_2_delay SMALLINT(5);
ALTER TABLE npc_text CHANGE COLUMN em2_5 em2_2 SMALLINT(5);

ALTER TABLE npc_text CHANGE COLUMN em3_0 em3_0_delay SMALLINT(5);
ALTER TABLE npc_text CHANGE COLUMN em3_1 em3_0 SMALLINT(5);
ALTER TABLE npc_text CHANGE COLUMN em3_2 em3_1_delay SMALLINT(5);
ALTER TABLE npc_text CHANGE COLUMN em3_3 em3_1 SMALLINT(5);
ALTER TABLE npc_text CHANGE COLUMN em3_4 em3_2_delay SMALLINT(5);
ALTER TABLE npc_text CHANGE COLUMN em3_5 em3_2 SMALLINT(5);

ALTER TABLE npc_text CHANGE COLUMN em4_0 em4_0_delay SMALLINT(5);
ALTER TABLE npc_text CHANGE COLUMN em4_1 em4_0 SMALLINT(5);
ALTER TABLE npc_text CHANGE COLUMN em4_2 em4_1_delay SMALLINT(5);
ALTER TABLE npc_text CHANGE COLUMN em4_3 em4_1 SMALLINT(5);
ALTER TABLE npc_text CHANGE COLUMN em4_4 em4_2_delay SMALLINT(5);
ALTER TABLE npc_text CHANGE COLUMN em4_5 em4_2 SMALLINT(5);

ALTER TABLE npc_text CHANGE COLUMN em5_0 em5_0_delay SMALLINT(5);
ALTER TABLE npc_text CHANGE COLUMN em5_1 em5_0 SMALLINT(5);
ALTER TABLE npc_text CHANGE COLUMN em5_2 em5_1_delay SMALLINT(5);
ALTER TABLE npc_text CHANGE COLUMN em5_3 em5_1 SMALLINT(5);
ALTER TABLE npc_text CHANGE COLUMN em5_4 em5_2_delay SMALLINT(5);
ALTER TABLE npc_text CHANGE COLUMN em5_5 em5_2 SMALLINT(5);

ALTER TABLE npc_text CHANGE COLUMN em6_0 em6_0_delay SMALLINT(5);
ALTER TABLE npc_text CHANGE COLUMN em6_1 em6_0 SMALLINT(5);
ALTER TABLE npc_text CHANGE COLUMN em6_2 em6_1_delay SMALLINT(5);
ALTER TABLE npc_text CHANGE COLUMN em6_3 em6_1 SMALLINT(5);
ALTER TABLE npc_text CHANGE COLUMN em6_4 em6_2_delay SMALLINT(5);
ALTER TABLE npc_text CHANGE COLUMN em6_5 em6_2 SMALLINT(5);

ALTER TABLE npc_text CHANGE COLUMN em7_0 em7_0_delay SMALLINT(5);
ALTER TABLE npc_text CHANGE COLUMN em7_1 em7_0 SMALLINT(5);
ALTER TABLE npc_text CHANGE COLUMN em7_2 em7_1_delay SMALLINT(5);
ALTER TABLE npc_text CHANGE COLUMN em7_3 em7_1 SMALLINT(5);
ALTER TABLE npc_text CHANGE COLUMN em7_4 em7_2_delay SMALLINT(5);
ALTER TABLE npc_text CHANGE COLUMN em7_5 em7_2 SMALLINT(5);

