-- Adding subtables

-- Adding comments about fields

update `dbdocstable` set `languageId`=0, `tableName`='dbscripts_on_go_template_use', `tableNotes`='This table holds scripts activated when a character uses a gameobject (like door, chest, button so on).' where tableId=41;
update `dbdocsfields` set `FieldComment` = 'Gameobject ID (See gameobject_template.entry).', `fieldNotes` = 'Gameobject ID (See gameobject_template.entry).<br />Note that commands with source = Unit should not be used here. The correct source may be defined via &quot;buddy&quot; or flag mechanic, see below.<br />The script may contain several commands with identical id. Execution of these commands is not synchronized but the sequence is uniquely defined by "delay" parameter.' where `fieldId`= '404' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Delay (sec).', `fieldNotes` = 'Delay in seconds.' where `fieldId`= '403' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Script command.', `fieldNotes` = 'Script command.<br />¬subtable:36¬' where `fieldId`= '394' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Command parameter, see command description.', `fieldNotes` = 'Command parameter, see command description.' where `fieldId`= '401' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Command parameter, see command description.', `fieldNotes` = 'Command parameter, see command description.' where `fieldId`= '402' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Command parameter, see command description.', `fieldNotes` = 'Command parameter, see command description.' where `fieldId`= '397' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Command parameter, see command description.', `fieldNotes` = 'Command parameter, see command description.' where `fieldId`= '398' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Command parameter, see command description.', `fieldNotes` = 'Command parameter, see command description.' where `fieldId`= '399' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Command parameter, see command description.', `fieldNotes` = 'Command parameter, see command description.' where `fieldId`= '400' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Position X.', `fieldNotes` = 'X of position - for commands requiring position.' where `fieldId`= '407' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Position Y.', `fieldNotes` = 'Y of position - for commands requiring position.' where `fieldId`= '408' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Position Z.', `fieldNotes` = 'Z of position - for commands requiring position.' where `fieldId`= '409' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Orientation angle (0 to 2*Pi).', `fieldNotes` = 'Orientation angle (0 to 2*Pi): 0 north, Pi south - for commands requiring position.' where `fieldId`= '405' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Textual comment.', `fieldNotes` = 'Textual comment, ignored by the core.' where `fieldId`= '395' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Creature ID (creature_template.entry) for changing source/target.', `fieldNotes` = 'Creature ID (creature_template.entry) for changing source/target.' where `fieldId`= '393' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Command flags.', `fieldNotes` = 'Command flags (see enum ScriptInfoDataFlags in ScriptMgr.h).<br />Default cast direction: source/buddy -> target, flags can change this.<br />¬subtable:37¬' where `fieldId`= '396' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Radius for the buddy search.', `fieldNotes` = 'Radius, in which the buddy will be searched. For changing source/target mechanic.' where `fieldId`= '406' and `languageId`= 0;

update `dbdocstable` set `languageId`=0, `tableName`='dbscripts_on_go_use', `tableNotes`='This table holds scripts activated when a character uses either door or button. This script, bound to the GameObject GUID, does not override the script bound to the GameObject entry, if any. If both scripts are defined, they are executed sequentially, the script from this table activates after the script from dbscripts_on_go_template_use.' where tableId=42;
update `dbdocsfields` set `FieldComment` = 'Gameobject GUID (See gameobject.guid).', `fieldNotes` = 'Gameobject GUID (See gameobject.guid).<br />Note that commands with source = Unit will be ineffective here because source = GameObject and target = Player. The correct source may be defined via &quot;buddy&quot; or flag mechanic, see below.<br />The script may contain several commands with identical id. Execution of these commands is not synchronized but the sequence is uniquely defined by "delay" parameter.' where `fieldId`= '421' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Delay (sec).', `fieldNotes` = 'Delay in seconds.' where `fieldId`= '420' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Script command.', `fieldNotes` = 'Script command.<br />¬subtable:36¬' where `fieldId`= '411' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Command parameter, see command description.', `fieldNotes` = 'Command parameter, see command description.' where `fieldId`= '418' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Command parameter, see command description.', `fieldNotes` = 'Command parameter, see command description.' where `fieldId`= '419' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Command parameter, see command description.', `fieldNotes` = 'Command parameter, see command description.' where `fieldId`= '414' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Command parameter, see command description.', `fieldNotes` = 'Command parameter, see command description.' where `fieldId`= '415' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Command parameter, see command description.', `fieldNotes` = 'Command parameter, see command description.' where `fieldId`= '416' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Command parameter, see command description.', `fieldNotes` = 'Command parameter, see command description.' where `fieldId`= '417' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Position X.', `fieldNotes` = 'X of position - for commands requiring position.' where `fieldId`= '424' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Position Y.', `fieldNotes` = 'Y of position - for commands requiring position.' where `fieldId`= '425' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Position Z.', `fieldNotes` = 'Z of position - for commands requiring position.' where `fieldId`= '426' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Orientation angle (0 to 2*Pi).', `fieldNotes` = 'Orientation angle (0 to 2*Pi): 0 north, Pi south - for commands requiring position.' where `fieldId`= '422' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Textual comment.', `fieldNotes` = 'Textual comment, ignored by the core.' where `fieldId`= '412' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Creature ID (creature_template.entry) for changing source/target.', `fieldNotes` = 'Creature ID (creature_template.entry) for changing source/target.' where `fieldId`= '410' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Command flags.', `fieldNotes` = 'Command flags (see enum ScriptInfoDataFlags in ScriptMgr.h).<br />Default cast direction: source/buddy -> target, flags can change this.<br />¬subtable:37¬' where `fieldId`= '413' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Radius for the buddy search.', `fieldNotes` = 'Radius, in which the buddy will be searched. For changing source/target mechanic.' where `fieldId`= '423' and `languageId`= 0;

update `dbdocstable` set `languageId`=0, `tableName`='dbscripts_on_gossip', `tableNotes`='This table holds scripts mentioned in the gossip_menu and gossip_menu_item tables. In the latter case, the parameters depend on object type (GameObject or Unit) of the object having such gossip: for GO, source = Player and target = GameObject; for Unit, source = Unit and target = Player. In the former case, source = Player and target = Unit. This all is rather funny, isn\'t this?<br />The scripts &quot;on talking to gameobject&quot; are implemented instead with dbscripts_on_go_template_use.' where tableId=43;
update `dbdocsfields` set `FieldComment` = 'Gossip script ID.', `fieldNotes` = 'Gossip script ID (See gossip_menu.script_id, gossip_menu_option.action_script_id).<br />The script may contain several commands with identical id. Execution of these commands is not synchronized but the sequence is uniquely defined by "delay" parameter.' where `fieldId`= '438' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Delay (sec).', `fieldNotes` = 'Delay in seconds.' where `fieldId`= '437' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Script command.', `fieldNotes` = 'Script command.<br />¬subtable:36¬' where `fieldId`= '428' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Command parameter, see command description.', `fieldNotes` = 'Command parameter, see command description.' where `fieldId`= '435' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Command parameter, see command description.', `fieldNotes` = 'Command parameter, see command description.' where `fieldId`= '436' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Command parameter, see command description.', `fieldNotes` = 'Command parameter, see command description.' where `fieldId`= '431' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Command parameter, see command description.', `fieldNotes` = 'Command parameter, see command description.' where `fieldId`= '432' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Command parameter, see command description.', `fieldNotes` = 'Command parameter, see command description.' where `fieldId`= '433' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Command parameter, see command description.', `fieldNotes` = 'Command parameter, see command description.' where `fieldId`= '434' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Position X.', `fieldNotes` = 'X of position - for commands requiring position.' where `fieldId`= '441' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Position Y.', `fieldNotes` = 'Y of position - for commands requiring position.' where `fieldId`= '442' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Position Z.', `fieldNotes` = 'Z of position - for commands requiring position.' where `fieldId`= '443' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Orientation angle (0 to 2*Pi).', `fieldNotes` = 'Orientation angle (0 to 2*Pi): 0 north, Pi south - for commands requiring position.' where `fieldId`= '439' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Textual comment.', `fieldNotes` = 'Textual comment, ignored by the core.' where `fieldId`= '429' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Creature ID (creature_template.entry) for changing source/target.', `fieldNotes` = 'Creature ID (creature_template.entry) for changing source/target.' where `fieldId`= '427' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Command flags.', `fieldNotes` = 'Command flags (see enum ScriptInfoDataFlags in ScriptMgr.h).<br />Default cast direction: source/buddy -> target, flags can change this.<br />¬subtable:37¬' where `fieldId`= '430' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Radius for the buddy search.', `fieldNotes` = 'Radius, in which the buddy will be searched. For changing source/target mechanic.' where `fieldId`= '440' and `languageId`= 0;

update `dbdocstable` set `languageId`=0, `tableName`='dbscripts_on_quest_end', `tableNotes`='This table holds scripts mentioned in the quest_template table. Here source = questrewarder, target = Player.' where tableId=44;
update `dbdocsfields` set `FieldComment` = 'Quest end script ID (See quest_template.CompleteScript).', `fieldNotes` = 'Quest end script ID (See quest_template.CompleteScript).<br />The script may contain several commands with identical id. Execution of these commands is not synchronized but the sequence is uniquely defined by "delay" parameter.' where `fieldId`= '455' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Delay (sec).', `fieldNotes` = 'Delay in seconds.' where `fieldId`= '454' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Script command.', `fieldNotes` = 'Script command.<br />¬subtable:36¬' where `fieldId`= '445' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Command parameter, see command description.', `fieldNotes` = 'Command parameter, see command description.' where `fieldId`= '452' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Command parameter, see command description.', `fieldNotes` = 'Command parameter, see command description.' where `fieldId`= '453' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Command parameter, see command description.', `fieldNotes` = 'Command parameter, see command description.' where `fieldId`= '448' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Command parameter, see command description.', `fieldNotes` = 'Command parameter, see command description.' where `fieldId`= '449' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Command parameter, see command description.', `fieldNotes` = 'Command parameter, see command description.' where `fieldId`= '450' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Command parameter, see command description.', `fieldNotes` = 'Command parameter, see command description.' where `fieldId`= '451' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Position X.', `fieldNotes` = 'X of position - for commands requiring position.' where `fieldId`= '458' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Position Y.', `fieldNotes` = 'Y of position - for commands requiring position.' where `fieldId`= '459' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Position Z.', `fieldNotes` = 'Z of position - for commands requiring position.' where `fieldId`= '460' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Orientation angle (0 to 2*Pi).', `fieldNotes` = 'Orientation angle (0 to 2*Pi): 0 north, Pi south - for commands requiring position.' where `fieldId`= '456' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Textual comment.', `fieldNotes` = 'Textual comment, ignored by the core.' where `fieldId`= '446' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Creature ID (creature_template.entry) for changing source/target.', `fieldNotes` = 'Creature ID (creature_template.entry) for changing source/target.' where `fieldId`= '444' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Command flags.', `fieldNotes` = 'Command flags (see enum ScriptInfoDataFlags in ScriptMgr.h).<br />Default cast direction: source/buddy -> target, flags can change this.<br />¬subtable:37¬' where `fieldId`= '447' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Radius for the buddy search.', `fieldNotes` = 'Radius, in which the buddy will be searched. For changing source/target mechanic.' where `fieldId`= '457' and `languageId`= 0;

update `dbdocstable` set `languageId`=0, `tableName`='dbscripts_on_quest_start', `tableNotes`='This table holds scripts mentioned in the quest_template table. Here source = questgiver, target = Player.' where tableId=45;
update `dbdocsfields` set `FieldComment` = 'Quest start script ID (See quest_template.StartScript).', `fieldNotes` = 'Quest start script ID (See quest_template.StartScript).<br />The script may contain several commands with identical id. Execution of these commands is not synchronized but the sequence is uniquely defined by "delay" parameter.' where `fieldId`= '472' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Delay (sec).', `fieldNotes` = 'Delay in seconds.' where `fieldId`= '471' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Script command.', `fieldNotes` = 'Script command.<br />¬subtable:36¬' where `fieldId`= '462' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Command parameter, see command description.', `fieldNotes` = 'Command parameter, see command description.' where `fieldId`= '469' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Command parameter, see command description.', `fieldNotes` = 'Command parameter, see command description.' where `fieldId`= '470' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Command parameter, see command description.', `fieldNotes` = 'Command parameter, see command description.' where `fieldId`= '465' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Command parameter, see command description.', `fieldNotes` = 'Command parameter, see command description.' where `fieldId`= '466' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Command parameter, see command description.', `fieldNotes` = 'Command parameter, see command description.' where `fieldId`= '467' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Command parameter, see command description.', `fieldNotes` = 'Command parameter, see command description.' where `fieldId`= '468' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Position X.', `fieldNotes` = 'X of position - for commands requiring position.' where `fieldId`= '475' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Position Y.', `fieldNotes` = 'Y of position - for commands requiring position.' where `fieldId`= '476' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Position Z.', `fieldNotes` = 'Z of position - for commands requiring position.' where `fieldId`= '477' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Orientation angle (0 to 2*Pi).', `fieldNotes` = 'Orientation angle (0 to 2*Pi): 0 north, Pi south - for commands requiring position.' where `fieldId`= '473' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Textual comment.', `fieldNotes` = 'Textual comment, ignored by the core.' where `fieldId`= '463' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Creature ID (creature_template.entry) for changing source/target.', `fieldNotes` = 'Creature ID (creature_template.entry) for changing source/target.' where `fieldId`= '461' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Command flags.', `fieldNotes` = 'Command flags (see enum ScriptInfoDataFlags in ScriptMgr.h).<br />Default cast direction: source/buddy -> target, flags can change this.<br />¬subtable:37¬' where `fieldId`= '464' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Radius for the buddy search.', `fieldNotes` = 'Radius, in which the buddy will be searched. For changing source/target mechanic.' where `fieldId`= '474' and `languageId`= 0;

update `dbdocstable` set `languageId`=0, `tableName`='dbscripts_on_spell', `tableNotes`='This table holds scripts triggered by spells with EFFECT_DUMMY (3) or EFFECT_SCRIPT_EFFECT (77). Here source = caster, target = unitTarget.<br />Note that if the spell contains more than 1 effect of such type, this script will be set up for the single effect only, namely for one with the least effect number.' where tableId=46;
update `dbdocsfields` set `FieldComment` = 'Spell ID (See Spell.dbc).', `fieldNotes` = 'Spell ID (See Spell.dbc).<br />The script may contain several commands with identical id. Execution of these commands is not synchronized but the sequence is uniquely defined by "delay" parameter.' where `fieldId`= '489' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Delay (sec).', `fieldNotes` = 'Delay in seconds.' where `fieldId`= '488' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Script command.', `fieldNotes` = 'Script command.<br />¬subtable:36¬' where `fieldId`= '479' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Command parameter, see command description.', `fieldNotes` = 'Command parameter, see command description.' where `fieldId`= '486' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Command parameter, see command description.', `fieldNotes` = 'Command parameter, see command description.' where `fieldId`= '487' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Command parameter, see command description.', `fieldNotes` = 'Command parameter, see command description.' where `fieldId`= '482' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Command parameter, see command description.', `fieldNotes` = 'Command parameter, see command description.' where `fieldId`= '483' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Command parameter, see command description.', `fieldNotes` = 'Command parameter, see command description.' where `fieldId`= '484' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Command parameter, see command description.', `fieldNotes` = 'Command parameter, see command description.' where `fieldId`= '495' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Position X.', `fieldNotes` = 'X of position - for commands requiring position.' where `fieldId`= '492' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Position Y.', `fieldNotes` = 'Y of position - for commands requiring position.' where `fieldId`= '493' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Position Z.', `fieldNotes` = 'Z of position - for commands requiring position.' where `fieldId`= '494' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Orientation angle (0 to 2*Pi).', `fieldNotes` = 'Orientation angle (0 to 2*Pi): 0 north, Pi south - for commands requiring position.' where `fieldId`= '490' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Textual comment.', `fieldNotes` = 'Textual comment, ignored by the core.' where `fieldId`= '480' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Creature ID (creature_template.entry) for changing source/target.', `fieldNotes` = 'Creature ID (creature_template.entry) for changing source/target.' where `fieldId`= '478' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Command flags.', `fieldNotes` = 'Command flags (see enum ScriptInfoDataFlags in ScriptMgr.h).<br />Default cast direction: source/buddy -> target, flags can change this.<br />¬subtable:37¬' where `fieldId`= '481' and `languageId`= 0;
update `dbdocsfields` set `FieldComment` = 'Radius for the buddy search.', `fieldNotes` = 'Radius, in which the buddy will be searched. For changing source/target mechanic.' where `fieldId`= '491' and `languageId`= 0;
